[package]
name = "schnauzer"
version = "0.1.2"
edition = "2021"
license = "MIT OR Apache-2.0"
repository = "https://github.com/Arsynth/schnauzer"
keywords = ["macho", "mach-o", "binary"]
categories = ["command-line-interface"]
description = "Library for parsing Mach-O files"
exclude = [
    "testable/*"
]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
scroll = "0.11.0"